name: Publish canary of Artillery CLI to npm
on:
  push:
    branches:
      - main
    paths:
      - 'packages/artillery/**'
      - 'packages/artillery-plugin-expect/**'
      - 'packages/artillery-plugin-publish-metrics/**'      
      - 'packages/artillery-plugin-metrics-by-endpoint/**'
      - 'packages/artillery-plugin-apdex/**'
      - 'packages/artillery-plugin-ensure/**'
      - 'packages/core/**'
      - 'packages/commons/**'
      - 'packages/artillery-engine-playwright/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@artilleryio'
      - run: |
          # Get current version of artillery from package.json, and replace with one
          # than includes the current commit hash
          ARTILLERY_VERSION=$(node -p "require('./packages/artillery/package.json').version")
          sed -i "s/\"version\": \".*\"/\"version\": \"${ARTILLERY_VERSION}-$(git rev-parse --short HEAD)\"/" packages/artillery/package.json
          npm -w artillery publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
